spring:
  h2: # 設定 H2 資料庫相關配置
    console:
      enabled: true
      path: /h2-console
  datasource: # 設定資料庫相關配置
    url: jdbc:h2:file:./src/main/resources/data/ironman;AUTO_SERVER=true
    username: sa
    password: Ironman0924!
  jpa: # 設定 JPA 相關配置
    hibernate:
      ddl-auto: update
    database-platform: H2
    show-sql: true
    generate-ddl: false
  thymeleaf:
    cache: false    # 關閉 Cache
    encoding: UTF-8 # 編碼設定
    mode: HTML5     # 模式
    suffix: .html   # 檔案副檔名
    prefix: classpath:/templates/ # 檔案儲存位置
